# Generated by Django 4.2.3 on 2023-10-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
